### ISSUE TITLE
Fix dependency problem

### ISSUE THREAD

**Issue by onacit** [GedMarc/GuicedEE#2]
When tried with following dependency,

```
      <dependency>
        <!-- https://search.maven.org/artifact/com.guicedee.services/guice -->
        <groupId>com.guicedee.services</groupId>
        <artifactId>guice</artifactId>
        <version>1.2.0.1-jre11</version>
      </dependency>
```

Maven complains.

> Could not resolve dependencies for project ...: Failed to collect dependencies at com.guicedee.services:guice:jar:1.2.0.1-jre11: Failed to read artifact descriptor for com.guicedee.services:guice:jar:1.2.0.1-jre11: com.guicedee:versioner:pom:1.2.0.1-jre11 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Especially

```
com.guicedee:versioner:pom:1.2.0.1-jre11
```

**Comment by GedMarc** [comment]
erg oops 
https://mvnrepository.com/artifact/com.guicedee/versioner

**Comment by GedMarc** [comment]
ok on changing the versioning mechanism and coordinates examples got muddled, 
proper support on jdk17 took preference

**Comment by onacit** [comment]
Thanks. But I need to stick to 11.

**Comment by GedMarc** [comment]
yeah 100%, the default classifier is now 11 - support for 8 is dropped - 

The library compatibility tests are busy running after the last round of version updates, +- 30/60 mins

**Comment by GedMarc** [comment]
Mentioned version updates - https://github.com/GedMarc/GuicedEE-BOM/commit/0e883dea2c2f837b14a9a9172708ecb580a012a7

**Comment by GedMarc** [comment]
there we go - https://sbom.lift.sonatype.com/report/T1-0ff0976f7f21c391f20f-a59249c7b34fe-1644491884-531dba339c6f453e8d8af3d83356ee28

Seems to be taking forever to sync though, will be up soon

**Comment by GedMarc** [comment]
https://search.maven.org/artifact/com.guicedee.services/guice/1.2.2.1/jar
